// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// MonteCarloC
arma::vec MonteCarloC(double dLambda, double dMu, double dSigma2, int iB);
RcppExport SEXP _PS4Package_MonteCarloC(SEXP dLambdaSEXP, SEXP dMuSEXP, SEXP dSigma2SEXP, SEXP iBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type dLambda(dLambdaSEXP);
    Rcpp::traits::input_parameter< double >::type dMu(dMuSEXP);
    Rcpp::traits::input_parameter< double >::type dSigma2(dSigma2SEXP);
    Rcpp::traits::input_parameter< int >::type iB(iBSEXP);
    rcpp_result_gen = Rcpp::wrap(MonteCarloC(dLambda, dMu, dSigma2, iB));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PS4Package_MonteCarloC", (DL_FUNC) &_PS4Package_MonteCarloC, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_PS4Package(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
