// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CDynPoissonSim
arma::vec CDynPoissonSim(int iT, double dPhi, double dAlpha);
RcppExport SEXP _PS5Package_CDynPoissonSim(SEXP iTSEXP, SEXP dPhiSEXP, SEXP dAlphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type iT(iTSEXP);
    Rcpp::traits::input_parameter< double >::type dPhi(dPhiSEXP);
    Rcpp::traits::input_parameter< double >::type dAlpha(dAlphaSEXP);
    rcpp_result_gen = Rcpp::wrap(CDynPoissonSim(iT, dPhi, dAlpha));
    return rcpp_result_gen;
END_RCPP
}
// CNegAvgll
double CNegAvgll(arma::vec vY, arma::vec vPar);
RcppExport SEXP _PS5Package_CNegAvgll(SEXP vYSEXP, SEXP vParSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type vY(vYSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vPar(vParSEXP);
    rcpp_result_gen = Rcpp::wrap(CNegAvgll(vY, vPar));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PS5Package_CDynPoissonSim", (DL_FUNC) &_PS5Package_CDynPoissonSim, 3},
    {"_PS5Package_CNegAvgll", (DL_FUNC) &_PS5Package_CNegAvgll, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_PS5Package(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
