// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Cgjrgarchsim
List Cgjrgarchsim(int iT, double dOmega, double dAlpha, double dGamma, double dBeta);
RcppExport SEXP _PS6Package_Cgjrgarchsim(SEXP iTSEXP, SEXP dOmegaSEXP, SEXP dAlphaSEXP, SEXP dGammaSEXP, SEXP dBetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type iT(iTSEXP);
    Rcpp::traits::input_parameter< double >::type dOmega(dOmegaSEXP);
    Rcpp::traits::input_parameter< double >::type dAlpha(dAlphaSEXP);
    Rcpp::traits::input_parameter< double >::type dGamma(dGammaSEXP);
    Rcpp::traits::input_parameter< double >::type dBeta(dBetaSEXP);
    rcpp_result_gen = Rcpp::wrap(Cgjrgarchsim(iT, dOmega, dAlpha, dGamma, dBeta));
    return rcpp_result_gen;
END_RCPP
}
// CMap2Natural
double CMap2Natural(double dParTilde, double dLbound, double dUbound);
RcppExport SEXP _PS6Package_CMap2Natural(SEXP dParTildeSEXP, SEXP dLboundSEXP, SEXP dUboundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type dParTilde(dParTildeSEXP);
    Rcpp::traits::input_parameter< double >::type dLbound(dLboundSEXP);
    Rcpp::traits::input_parameter< double >::type dUbound(dUboundSEXP);
    rcpp_result_gen = Rcpp::wrap(CMap2Natural(dParTilde, dLbound, dUbound));
    return rcpp_result_gen;
END_RCPP
}
// CMap2Working
double CMap2Working(double dPar, double dLbound, double dUbound);
RcppExport SEXP _PS6Package_CMap2Working(SEXP dParSEXP, SEXP dLboundSEXP, SEXP dUboundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type dPar(dParSEXP);
    Rcpp::traits::input_parameter< double >::type dLbound(dLboundSEXP);
    Rcpp::traits::input_parameter< double >::type dUbound(dUboundSEXP);
    rcpp_result_gen = Rcpp::wrap(CMap2Working(dPar, dLbound, dUbound));
    return rcpp_result_gen;
END_RCPP
}
// CMap2NaturalAll
arma::vec CMap2NaturalAll(arma::vec vPar, double dLowerLimit, double dUpperLimit);
RcppExport SEXP _PS6Package_CMap2NaturalAll(SEXP vParSEXP, SEXP dLowerLimitSEXP, SEXP dUpperLimitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type vPar(vParSEXP);
    Rcpp::traits::input_parameter< double >::type dLowerLimit(dLowerLimitSEXP);
    Rcpp::traits::input_parameter< double >::type dUpperLimit(dUpperLimitSEXP);
    rcpp_result_gen = Rcpp::wrap(CMap2NaturalAll(vPar, dLowerLimit, dUpperLimit));
    return rcpp_result_gen;
END_RCPP
}
// CMap2WorkingAll
arma::vec CMap2WorkingAll(arma::vec vPar, double dLowerLimit, double dUpperLimit);
RcppExport SEXP _PS6Package_CMap2WorkingAll(SEXP vParSEXP, SEXP dLowerLimitSEXP, SEXP dUpperLimitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type vPar(vParSEXP);
    Rcpp::traits::input_parameter< double >::type dLowerLimit(dLowerLimitSEXP);
    Rcpp::traits::input_parameter< double >::type dUpperLimit(dUpperLimitSEXP);
    rcpp_result_gen = Rcpp::wrap(CMap2WorkingAll(vPar, dLowerLimit, dUpperLimit));
    return rcpp_result_gen;
END_RCPP
}
// CStartingValues
arma::vec CStartingValues(arma::vec vY);
RcppExport SEXP _PS6Package_CStartingValues(SEXP vYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type vY(vYSEXP);
    rcpp_result_gen = Rcpp::wrap(CStartingValues(vY));
    return rcpp_result_gen;
END_RCPP
}
// CNegAvgLL
List CNegAvgLL(arma::vec vY, arma::vec vPar);
RcppExport SEXP _PS6Package_CNegAvgLL(SEXP vYSEXP, SEXP vParSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type vY(vYSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vPar(vParSEXP);
    rcpp_result_gen = Rcpp::wrap(CNegAvgLL(vY, vPar));
    return rcpp_result_gen;
END_RCPP
}
// CNegAvgLLlink
double CNegAvgLLlink(arma::vec vY, arma::vec vParTilde);
RcppExport SEXP _PS6Package_CNegAvgLLlink(SEXP vYSEXP, SEXP vParTildeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type vY(vYSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vParTilde(vParTildeSEXP);
    rcpp_result_gen = Rcpp::wrap(CNegAvgLLlink(vY, vParTilde));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PS6Package_Cgjrgarchsim", (DL_FUNC) &_PS6Package_Cgjrgarchsim, 5},
    {"_PS6Package_CMap2Natural", (DL_FUNC) &_PS6Package_CMap2Natural, 3},
    {"_PS6Package_CMap2Working", (DL_FUNC) &_PS6Package_CMap2Working, 3},
    {"_PS6Package_CMap2NaturalAll", (DL_FUNC) &_PS6Package_CMap2NaturalAll, 3},
    {"_PS6Package_CMap2WorkingAll", (DL_FUNC) &_PS6Package_CMap2WorkingAll, 3},
    {"_PS6Package_CStartingValues", (DL_FUNC) &_PS6Package_CStartingValues, 1},
    {"_PS6Package_CNegAvgLL", (DL_FUNC) &_PS6Package_CNegAvgLL, 2},
    {"_PS6Package_CNegAvgLLlink", (DL_FUNC) &_PS6Package_CNegAvgLLlink, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_PS6Package(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
